In [1]:
%load_ext autoreload
%autoreload 2
import dask
import dask.distributed
from dask_util import DaskClient
import dask_util
import numpy as np

In [2]:
local_params = {
    "n_workers":4, 
    "processes" : True, 
    "dashboard_address" : 'localhost:7777'
    
}

client = DaskClient(local_params=local_params)

In [3]:
dask_util.save(client, 'client.dask')

In [4]:
client2 = dask_util.load('client.dask')

In [5]:
client.getWorkerIds()

['tcp://127.0.0.1:36219',
 'tcp://127.0.0.1:38901',
 'tcp://127.0.0.1:42105',
 'tcp://127.0.0.1:42269']

In [9]:
client.getClient()

Connection method: Cluster object,Cluster type: distributed.LocalCluster
Dashboard: http://127.0.0.1:7777/status,
Dashboard: http://127.0.0.1:7777/status,Workers: 4
Total threads: 8,Total memory: 3.84 GiB
Status: running,Using processes: True
Comm: tcp://127.0.0.1:34611,Workers: 4
Dashboard: http://127.0.0.1:7777/status,Total threads: 8
Started: Just now,Total memory: 3.84 GiB
Comm: tcp://127.0.0.1:38901,Total threads: 2
Dashboard: http://127.0.0.1:36675/status,Memory: 0.96 GiB
Nanny: tcp://127.0.0.1:33503,


In [4]:
%load_ext autoreload
%autoreload 2
import SepVector
from __pyDaskVector import DaskVector
from __pyDaskOperator import DaskOperator, DaskSpread
import Hypercube
import pyOperator as Op


WARNING! DATAPATH not found. The folder /tmp will be used to write binary files


/usr/local/lib/python3.9/dist-packages/numpy/core/getlimits.py:500: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/usr/local/lib/python3.9/dist-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/usr/local/lib/python3.9/dist-packages/numpy/core/getlimits.py:500: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/usr/local/lib/python3.9/dist-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)


In [31]:

ns = [10,10,10]
os = [0,0,0]
ds = [1,1,1]
chunks = (1,1,3)

ax = Hypercube.axis(n=1, o=1, d=1)
hyp = Hypercube.hypercube(ns=ns, ds=ds, os=os)
vec = SepVector.getSepVector(ns=ns, ds=ds, os=os)
vec.set(1)

floatVector
Axis 1: n=10	o=0.000000	d=1.000000
Axis 2: n=20	o=0.000000	d=1.000000
Axis 3: n=30	o=0.000000	d=1.000000

In [6]:
# option 1
# creating from scratch
data = DaskVector(client, vecCls=SepVector.floatVector, ns=ns, ds=ds, os=os, chunks=chunks)

In [32]:
# option 2
# creating from existing in-memory SepVector
daskVec = DaskVector(client, from_vector=vec, chunks=chunks)

In [33]:
client.getClient().has_what()

{'tcp://127.0.0.1:34237': ('from_subspace-f0b5fcd03548afb542374e0d8aba3bb0',
  'cloneSpace-7c322409-2310-44c1-ad84-2bae572fd1b7-3',
  'cloneSpace-2b4f4923-d6a1-4094-be05-88944ca6af3b-0',
  'from_subspace-204652c145d7b3a09d389968ed7c464d',
  'from_subspace-7a3f5d23ef600e8936f1891b7bc2fab9',
  'window-5e632e848ae015a5c1696cbb3cd10cf0'),
 'tcp://127.0.0.1:38923': ('cloneSpace-7c322409-2310-44c1-ad84-2bae572fd1b7-1',
  'cloneSpace-2b4f4923-d6a1-4094-be05-88944ca6af3b-1',
  'from_subspace-380fbcf6a612ef111739783c18ecedfc',
  'from_subspace-c6501d0cf0039f65b5f7caa658b61748',
  'window-b641ee8cddc00a78cdd2702ee8ff0844'),
 'tcp://127.0.0.1:43503': ('from_subspace-58393ec8ca281122af42540c29cb0319',
  'cloneSpace-7c322409-2310-44c1-ad84-2bae572fd1b7-2',
  'cloneSpace-2b4f4923-d6a1-4094-be05-88944ca6af3b-2',
  'from_subspace-28ad4126a55a961856eca788caf01225',
  'from_subspace-06d23f771fac8909aefb5f4f23eb4019',
  'from_subspace-231d1b46f7488cf3bc0a391cdd45de6b',
  'from_subspace-e9964cad3639cda723e0e03ae536abb3',
  'from_subspace-871aae82a564c2baffe4c9988e3d7a64',
  'from_subspace-75c66b80c90265deed848ea7dc11f3ef',
  '__add__-16e5e1f4-7f05-4135-a25a-3e50aa53ab90-2',
  '__add__-16e5e1f4-7f05-4135-a25a-3e50aa53ab90-1',
  '__add__-16e5e1f4-7f05-4135-a25a-3e50aa53ab90-0',
  '__add__-16e5e1f4-7f05-4135-a25a-3e50aa53ab90-3',
  'cloneSpace-2b4f4923-d6a1-4094-be05-88944ca6af3b-3',
  'from_subspace-814d3ad694f19cd21ed96cc79b50bf8d',
  'from_subspace-7ba39f91d324e12b31df1d5915fa7eaa',
  'from_subspace-4df149340224c6587ac6503b29cdabcc'),
 'tcp://127.0.0.1:45537': ('cloneSpace-7c322409-2310-44c1-ad84-2bae572fd1b7-0',
  'from_subspace-3ad8ac15c9c6baa84c6eaaf756d021e2',
  'window-12512627333364c4948b5a95e064a320')}

In [9]:
# daskVec[3:5,:] = 0

In [28]:
daskVec[:]

[array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=float32)]

In [11]:
spread_op = DaskSpread(client, data)

In [12]:
spread_op.workers

{('tcp://127.0.0.1:34237',),
 ('tcp://127.0.0.1:38923',),
 ('tcp://127.0.0.1:43503',),
 ('tcp://127.0.0.1:45537',)}

In [14]:
scaleOp = DaskOperator(client, opCls=Op.scalingOp, domain=daskVec, range=data, op_args=[4])

In [15]:
data[:]

[array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=float32)]

In [16]:
scaleOp.forward(False, daskVec, data)

In [17]:
data[:]

/usr/local/lib/python3.9/dist-packages/numpy/core/getlimits.py:500: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/usr/local/lib/python3.9/dist-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/usr/local/lib/python3.9/dist-packages/numpy/core/getlimits.py:500: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/usr/local/lib/python3.9/dist-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/usr/local/lib/python3.9/dist-packages/numpy/core/getlimits.py:500: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is z

[array([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]], dtype=float32),
 array([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]], dtype=float32),
 array([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]], dtype=float32),
 array([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]], dtype=float32)]

In [24]:
scaleOp.adjoint(False, daskVec, data)

In [25]:
daskVec[:]

[array([[16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.]], dtype=float32),
 array([[16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.]], dtype=float32),
 array([[16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.]], dtype=float32),
 array([[16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.]], dtype=float32)]