In [1]:
import dask
import dask.distributed
from dask_util import DaskClient
import numpy as np

In [2]:
local_params = {
    "n_workers":4, 
    "processes" : True, 
    "dashboard_address" : 'localhost:7777'
    
}

client = DaskClient(local_params=local_params)

2023-01-24 23:56:19,627 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-worker-space/worker-7nq0ugrj', purging
2023-01-24 23:56:19,627 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-worker-space/worker-blh00gzr', purging


In [3]:
client.getWorkerIds()

['tcp://127.0.0.1:36601',
 'tcp://127.0.0.1:37805',
 'tcp://127.0.0.1:38327',
 'tcp://127.0.0.1:40121']

In [4]:
%load_ext autoreload
%autoreload 2
import SepVector
import __pyDaskVector as DaskVector
import Hypercube
import pyOperator as Op


WARNING! DATAPATH not found. The folder /tmp will be used to write binary files


In [65]:

ns = [10,10]
os = [0,0]
ds = [1,1]
chunks = (1,4)

ax = Hypercube.axis(n=1, o=1, d=1)
hyp = Hypercube.hypercube(ns=ns, ds=ds, os=os)
vec = SepVector.getSepVector(ns=ns, ds=ds, os=os, storage='dataFloat')
vec.rand()

floatVector
Axis 1: n=10	o=0.000000	d=1.000000
Axis 2: n=10	o=0.000000	d=1.000000

In [66]:
# option 1
# creating from scratch
daskVec = DaskVector.DaskVector(client, vecCls=SepVector.floatVector, ns=ns, ds=ds, os=os, chunks=chunks)

In [67]:
# option 2
# creating from existing in-memory SepVector
daskVec = DaskVector.DaskVector(client, from_vector=vec, chunks=chunks)

In [68]:
client.getClient().has_what()

{'tcp://127.0.0.1:36601': ('from_subspace-a0727dc5ce20e9109c54c622af2a3d17',
  'cloneSpace-479a3ce7-5da4-4ed5-8bed-0d2da2b6e685-1',
  'cloneSpace-58d37b90-b23f-4432-a936-bfb1a3b8247a-1',
  'from_subspace-bc0d506e01fc817d60e1e7434aaad46e',
  'from_subspace-4481b53c0c4944a4821f67217106ad40',
  'from_subspace-7c3cfcc01466018bada8fa1cf633df4c',
  'cloneSpace-4e0978dd-2065-488a-b26b-c665f4a0a504-0',
  'cloneSpace-7ee24046-917c-47b7-be41-d231d2d05cda-0',
  'clone-dd1eac9f-9ded-4503-9997-b11c2b9046de-0',
  'from_subspace-4672b00414604c08827bee72a1e98575',
  'from_subspace-1fb8108ef52eb44d79d0490acb86f0be',
  'from_subspace-a6a22bb7f14efb8c8708581c16f6f8b7',
  'window-18b4fb21f3875801ba53f8bf5c88fe71'),
 'tcp://127.0.0.1:37805': ('window-f0930706482bacad728474ac28efb2d7',),
 'tcp://127.0.0.1:38327': ('from_subspace-13cef8087fd6ee07ca19845e9f37c1ef',
  'cloneSpace-479a3ce7-5da4-4ed5-8bed-0d2da2b6e685-2',
  'from_subspace-d32655228f9edb02590481059342fc04',
  'from_subspace-3caae369c6e6c37fa3e66e4e42c70f71',
  'cloneSpace-58d37b90-b23f-4432-a936-bfb1a3b8247a-2',
  'from_subspace-da2e8422921fe89866d0f3c9f452b35b',
  'from_subspace-20aecb16243575146836aaf1cb269cd3',
  'cloneSpace-4e0978dd-2065-488a-b26b-c665f4a0a504-2',
  'cloneSpace-7ee24046-917c-47b7-be41-d231d2d05cda-2',
  'clone-dd1eac9f-9ded-4503-9997-b11c2b9046de-2',
  'from_subspace-9bcfd0e2f5ea79a59dfdca9e42074a00',
  'clone-dd1eac9f-9ded-4503-9997-b11c2b9046de-1',
  'from_subspace-0c44bf66b5ef9962f85878fd06fbec1f',
  'window-3b632611f5c5c5697a577ddc9745b352'),
 'tcp://127.0.0.1:40121': ('from_subspace-1a4a0241bb74aa0099246b6962d61e69',
  'cloneSpace-479a3ce7-5da4-4ed5-8bed-0d2da2b6e685-0',
  'cloneSpace-58d37b90-b23f-4432-a936-bfb1a3b8247a-0',
  'from_subspace-40a74731875db3ad322a525794af8377',
  'from_subspace-907302eaa020ff8cbb6ff937dad38608',
  'from_subspace-c06032502545e2250bfd5e875bb0764c',
  'cloneSpace-4e0978dd-2065-488a-b26b-c665f4a0a504-1',
  'cloneSpace-7ee24046-917c-47b7-be41-d231d2d05cda-1',
  'window-99ccfb7c4de820dbcbdbc8efbb6bd8e4')}

In [69]:
# daskVec[3:5,:] = 0

In [70]:
daskVec[:]

[array([[ 0.22454172,  0.3937715 ,  0.24113658,  0.4548885 ,  0.4210055 ,
          0.33687592,  0.4933609 ,  0.19773051, -0.2533118 ,  0.19013323],
        [-0.06843293,  0.41074312, -0.07280117,  0.20595132, -0.3038643 ,
         -0.20642994, -0.3451262 , -0.3874446 , -0.19960488,  0.04268946]],
       dtype=float32),
 array([[-0.03560471, -0.31896958,  0.09364534, -0.06291548,  0.31965658,
          0.22641692,  0.27713817,  0.3278949 , -0.18313749,  0.02789057],
        [ 0.29586187, -0.45859575, -0.07833794, -0.2146074 ,  0.3663712 ,
         -0.05107751,  0.4164197 , -0.49317494, -0.11218434, -0.14816014]],
       dtype=float32),
 array([[ 0.38063532, -0.4490441 ,  0.47268924,  0.13862613, -0.36722842,
         -0.15994634, -0.49176168,  0.0904456 ,  0.2507524 ,  0.46796697],
        [ 0.24651505,  0.11162136, -0.12414167, -0.4566657 ,  0.09011646,
          0.1764221 ,  0.23232037,  0.31344098, -0.40374935,  0.3842149 ]],
       dtype=float32),
 array([[-0.17743029,  0.30812564,

In [71]:

zeroOp = DaskVector.DaskOperator(client, opCls=Op.ZeroOp, domain=daskVec, range=daskVec)

In [72]:
# zeroOp.forward(False, daskVec, daskVec)

In [73]:
daskVec[:]

[array([[ 0.22454172,  0.3937715 ,  0.24113658,  0.4548885 ,  0.4210055 ,
          0.33687592,  0.4933609 ,  0.19773051, -0.2533118 ,  0.19013323],
        [-0.06843293,  0.41074312, -0.07280117,  0.20595132, -0.3038643 ,
         -0.20642994, -0.3451262 , -0.3874446 , -0.19960488,  0.04268946]],
       dtype=float32),
 array([[-0.03560471, -0.31896958,  0.09364534, -0.06291548,  0.31965658,
          0.22641692,  0.27713817,  0.3278949 , -0.18313749,  0.02789057],
        [ 0.29586187, -0.45859575, -0.07833794, -0.2146074 ,  0.3663712 ,
         -0.05107751,  0.4164197 , -0.49317494, -0.11218434, -0.14816014]],
       dtype=float32),
 array([[ 0.38063532, -0.4490441 ,  0.47268924,  0.13862613, -0.36722842,
         -0.15994634, -0.49176168,  0.0904456 ,  0.2507524 ,  0.46796697],
        [ 0.24651505,  0.11162136, -0.12414167, -0.4566657 ,  0.09011646,
          0.1764221 ,  0.23232037,  0.31344098, -0.40374935,  0.3842149 ]],
       dtype=float32),
 array([[-0.17743029,  0.30812564,

In [74]:
scaleOp = DaskVector.DaskOperator(client, opCls=Op.scalingOp, domain=daskVec, range=daskVec, op_args=[2])

In [91]:
data = daskVec.clone()
scaleOp.forward(False, daskVec, data)

In [92]:
data[:]

[array([[ 0.44908345,  0.787543  ,  0.48227316,  0.909777  ,  0.842011  ,
          0.67375183,  0.9867218 ,  0.39546102, -0.5066236 ,  0.38026646],
        [-0.13686585,  0.82148623, -0.14560233,  0.41190264, -0.6077286 ,
         -0.4128599 , -0.6902524 , -0.7748892 , -0.39920977,  0.08537892]],
       dtype=float32),
 array([[-0.07120942, -0.63793916,  0.18729068, -0.12583096,  0.63931316,
          0.45283383,  0.55427635,  0.6557898 , -0.36627498,  0.05578115],
        [ 0.59172374, -0.9171915 , -0.15667588, -0.4292148 ,  0.7327424 ,
         -0.10215503,  0.8328394 , -0.9863499 , -0.22436868, -0.2963203 ]],
       dtype=float32),
 array([[ 0., -0.,  0.,  0., -0., -0., -0.,  0.,  0.,  0.],
        [ 0.,  0., -0., -0.,  0.,  0.,  0.,  0., -0.,  0.]], dtype=float32),
 array([[-0.35486057,  0.6162513 ,  0.49898207, -0.37185407,  0.31659985,
          0.9142231 , -0.49151474, -0.91941345,  0.08109536,  0.24267538],
        [-0.74138874, -0.6509235 ,  0.26205423, -0.7190923 ,  0.877786

In [82]:
daskVec[:]

[array([[ 0.22454172,  0.3937715 ,  0.24113658,  0.4548885 ,  0.4210055 ,
          0.33687592,  0.4933609 ,  0.19773051, -0.2533118 ,  0.19013323],
        [-0.06843293,  0.41074312, -0.07280117,  0.20595132, -0.3038643 ,
         -0.20642994, -0.3451262 , -0.3874446 , -0.19960488,  0.04268946]],
       dtype=float32),
 array([[-0.03560471, -0.31896958,  0.09364534, -0.06291548,  0.31965658,
          0.22641692,  0.27713817,  0.3278949 , -0.18313749,  0.02789057],
        [ 0.29586187, -0.45859575, -0.07833794, -0.2146074 ,  0.3663712 ,
         -0.05107751,  0.4164197 , -0.49317494, -0.11218434, -0.14816014]],
       dtype=float32),
 array([[ 0.38063532, -0.4490441 ,  0.47268924,  0.13862613, -0.36722842,
         -0.15994634, -0.49176168,  0.0904456 ,  0.2507524 ,  0.46796697],
        [ 0.24651505,  0.11162136, -0.12414167, -0.4566657 ,  0.09011646,
          0.1764221 ,  0.23232037,  0.31344098, -0.40374935,  0.3842149 ]],
       dtype=float32),
 array([[-0.17743029,  0.30812564,

In [83]:
err = []
for v1, v2 in zip(data[:], daskVec[:]):
    err.append(np.linalg.norm(v1-2*v2))

In [84]:

err

[0.0, 0.0, 0.0, 0.0]